# Latest redis images
FROM redis:latest

# Environment variable with
ENV SENTINEL_QUORUM 2
ENV SENTINEL_DOWN_AFTER 1000
ENV SENTINEL_FAILOVER 1000

# Create and fill temp direcotry for config files 
RUN mkdir -p /redis
WORKDIR /redis

# Copy the configurations files
COPY ./LocalCluster/sentinel.conf .
COPY ./LocalCluster/sentinel-entrypoint.sh /usr/local/bin/

# Set authorization grants on the script
RUN chown redis:redis /redis/* && \
    chmod +x /usr/local/bin/sentinel-entrypoint.sh
	
EXPOSE 26379
 
ENTRYPOINT ["sentinel-entrypoint.sh"]